pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
        maven { url 'https://mavensync.zkoss.org/maven2' }
    }
}

rootProject.name = 'gestao-ambientes-zk'