CREATE TABLE usuarios (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          username VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          role VARCHAR(50) NOT NULL,
                          PRIMARY KEY (id)
);

CREATE TABLE alunos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        email VARCHAR(255) NOT NULL,
                        matricula VARCHAR(255) NOT NULL,
                        nome VARCHAR(255) NOT NULL,
                        PRIMARY KEY (id)
);

CREATE TABLE ambientes (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           capacidade_maxima INTEGER NOT NULL,
                           nome VARCHAR(255) NOT NULL,
                           tipo VARCHAR(255) NOT NULL,
                           PRIMARY KEY (id)
);

CREATE TABLE registros_presenca (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    data_hora_entrada TIMESTAMP(6) NOT NULL,
                                    data_hora_saida TIMESTAMP(6),
                                    aluno_id BIGINT NOT NULL,
                                    ambiente_id BIGINT NOT NULL,
                                    PRIMARY KEY (id)
);

ALTER TABLE alunos ADD CONSTRAINT uk_alunos_matricula UNIQUE (matricula);
ALTER TABLE registros_presenca ADD CONSTRAINT fk_registros_aluno FOREIGN KEY (aluno_id) REFERENCES alunos (id);
ALTER TABLE registros_presenca ADD CONSTRAINT fk_registros_ambiente FOREIGN KEY (ambiente_id) REFERENCES ambientes (id);
